	-----------------------------------------
	-- OBTIENE EL ULTIMO DIA HABIL DEL MES --
	-----------------------------------------
	PROCEDURE SP_027S_DIA_FIN(O_LEVANTA_BUSINESS OUT NOCOPY INTEGER, I_FECHA_INICIAL IN VARCHAR2) IS
		-- DECLARACION DE VARIABLES	
		V_FH_ULTIMO_MES VARCHAR2(15);
		V_NB_ULTIMO_MES VARCHAR2(30);
		V_NB_SABADO VARCHAR2(30);
		V_NB_DOMINGO VARCHAR2(30);
	BEGIN
		DBMS_OUTPUT.PUT_LINE('FECHA DE EJECUCION ' || I_FECHA_INICIAL);
	
		-- OBTENERMOS EL ULTIMO DIA DEL MES
		SELECT TO_CHAR(LAST_DAY(TO_DATE(I_FECHA_INICIAL, 'DD/MM/YYYY')), 'DD/MM/YYYY') FH_ULT_DIA_MES INTO V_FH_ULTIMO_MES FROM DUAL;
		DBMS_OUTPUT.PUT_LINE('ULTIMO DIA DE MES ' || V_FH_ULTIMO_MES);
		
		-- OBTENEMOS EL NOMBRE DEL PRIMER DIA DEL MES
		SELECT TO_CHAR(TO_DATE(V_FH_ULTIMO_MES, 'DD/MM/YYYY'), 'DAY') FH_ULTIMO_MES INTO V_NB_ULTIMO_MES FROM DUAL;
		DBMS_OUTPUT.PUT_LINE('NOMBRE DEL ULTIMO DIA DEL MES: ' || V_NB_ULTIMO_MES);
		
		-- OBTENEMOS EL NOMBRE DEL SABADO Y DOMINGO (INGLES O ESPAÑOL)
		SELECT TO_CHAR(TO_DATE('02/07/2011', 'DD/MM/YYYY'), 'DAY') NB_SABADO INTO V_NB_SABADO FROM DUAL;
		SELECT TO_CHAR(TO_DATE('03/07/2011', 'DD/MM/YYYY'), 'DAY') NB_DOMINGO INTO V_NB_DOMINGO FROM DUAL;
		
		-- VERIFICAMOS QUE EL ULTIMO DIA HABIL DEL MES NO SEA FIN DE SEMANA
		-- EN CASO DE SER ALGUN DIA DE SEMANA REALIZAMOS UNA CONSULTA PARA QUE NOS TRAIGA
		-- LA FECHA DEL VIERNES ANTERIOR 
		IF TRIM(V_NB_ULTIMO_MES) = TRIM(V_NB_SABADO) THEN
			-- SI ES SABADO SE ENVIA AL DIA ANTERIOR PARA SU EJECUCION Y CAMBIA EL ULTIMO DIA HABIL
			DBMS_OUTPUT.PUT_LINE('EL ULTIMO DIA DE MES ES SABADO POR LO CUAL NO SE EJECUTARA');
			SELECT TO_CHAR(LAST_DAY(TO_DATE(V_FH_ULTIMO_MES, 'DD/MM/YYYY')) - 1, 'DD/MM/YYYY') ultimo_dia_del_mes INTO V_FH_ULTIMO_MES FROM DUAL;
			DBMS_OUTPUT.PUT_LINE('ULTIMO DIA HABIL DEL MES ' || V_FH_ULTIMO_MES);
		ELSIF TRIM(V_NB_ULTIMO_MES) = TRIM(V_NB_DOMINGO) THEN
			-- SI ES DOMINGO SE ENVIA AL SIGUIENTE LUNES PARA SU EJECUCION Y CAMBIA EL PRIMER DIA HABIL
			DBMS_OUTPUT.PUT_LINE('EL ULTIMO DIA DE MES ES DOMINGO POR LO CUAL NO SE EJECUTARA');
			SELECT TO_CHAR(LAST_DAY(TO_DATE(V_FH_ULTIMO_MES, 'DD/MM/YYYY')) - 2, 'DD/MM/YYYY') ultimo_dia_del_mes INTO V_FH_ULTIMO_MES FROM DUAL;
			DBMS_OUTPUT.PUT_LINE('ULTIMO DIA HABIL DEL MES ' || V_FH_ULTIMO_MES);
		END IF;
		
		-- COMPARAMOS LA FECHA INPUT CON LA FECHA DEL ULTIMO DIA HABIL
		-- PARA SABER SI SE EJECUTARA EL BP
		IF I_FECHA_INICIAL = V_FH_ULTIMO_MES THEN
			O_LEVANTA_BUSINESS := 1;
		ELSE   
			O_LEVANTA_BUSINESS := 0;
		END IF;
		
		DBMS_OUTPUT.PUT_LINE('EL PROCESO SE EJECUTARA? ' || O_LEVANTA_BUSINESS);
	END SP_027S_DIA_FIN;
