create or replace
PACKAGE BODY  PG_MX_SICOCO_MT94X AS

	-------------------------------------------------------
	-- PROCEDIMIENTO QUE IDENTIFICA LAS CUENTAS A LAS QUE--
	-- SE COBRARA MENSUALIDAD PARA SICOCO                -- 
	-------------------------------------------------------

	PROCEDURE SP_132S_SICOCO_94X(O_CURSOR OUT NOCOPY PG_XX_UTILERIA.param_cursor) IS
	 BEGIN
		OPEN O_CURSOR FOR
		SELECT MT940.NB_CUENTA, MT940.NU_CODIGO_SICOCO, MT940.TX_TP_OPERACION, MT940.NB_CONTRATO, 
						MT940.NU_OPERACIONES,  MT940.NB_MONEDA, MT940.CD_CLIENTE_AAA, MT940.NU_PORCENTAJE,                      
						MT940.IM_COMISION_USD, MT940.IM_COMISION_MXN, MT940.IM_COMISION_EUR   
		FROM (SELECT  SUBSTR(T132.NB_CTA_COMISIONES,1,10) NB_CUENTA, TPO.NU_CODIGO_SICOCO, TPO.TX_TP_OPERACION, T040.NB_CONTRATO, 
								1 AS NU_OPERACIONES,  MND.NB_MONEDA, T132.CD_CLIENTE_AAA,IVA.NU_PORCENTAJE,                      
								CASE T132.CD_CLIENTE_AAA WHEN '1' THEN 0 ELSE TPO.IM_COMISION_USD END IM_COMISION_USD,
								CASE T132.CD_CLIENTE_AAA WHEN '1' THEN 0 ELSE TPO.IM_COMISION_MXN END IM_COMISION_MXN, 
								CASE T132.CD_CLIENTE_AAA WHEN '1' THEN 0 ELSE TPO.IM_COMISION_EUR END IM_COMISION_EUR,
								CASE T132.CD_CANAL WHEN 1 THEN 1 WHEN 2 THEN 1 ELSE 2 END Fila
					FROM TGM053_TIPO_OP_MX TPO, TGM132_CTARL_MX94X T132
					INNER JOIN TGM040_CTA_RLY_MX T040 ON  T132.CD_CTARL_MX94X = T040.CD_CTARL_MX94X 
					INNER JOIN TGM042_MONEDA_MX MND ON T132.CD_MONEDA = MND.CD_MONEDA
					INNER JOIN TGM041_IVA_MX IVA ON T132.CD_IVA = IVA.CD_IVA
					WHERE  T132.CD_MENSUALIDAD = 1 AND T132.TM_BAJA IS NULL
					AND T132.CD_MT940 = '1' AND TPO.TP_MENSAJE = '940') MT940, 
					(SELECT Rownum AS Fila FROM TGM132_CTARL_MX94X) Repetir
		WHERE MT940.Fila >= Repetir.Fila
		UNION ALL			
		SELECT MT941.NB_CUENTA , MT941.NU_CODIGO_SICOCO, MT941.TX_TP_OPERACION, MT941.CD_REFERENCIA_BNC, 
						MT941.NU_OPERACIONES,  MT941.NB_MONEDA, MT941.CD_CLIENTE_AAA, MT941.NU_PORCENTAJE,                      
						MT941.IM_COMISION_USD, MT941.IM_COMISION_MXN, MT941.IM_COMISION_EUR   
		FROM (SELECT  SUBSTR(T132.NB_CTA_COMISIONES,1,10) NB_CUENTA, TPO.NU_CODIGO_SICOCO, TPO.TX_TP_OPERACION, T132.CD_REFERENCIA_BNC, 
								1 AS NU_OPERACIONES,  MND.NB_MONEDA, T132.CD_CLIENTE_AAA,IVA.NU_PORCENTAJE,                      
								CASE T132.CD_CLIENTE_AAA WHEN '1' THEN 0 ELSE TPO.IM_COMISION_USD END IM_COMISION_USD,
								CASE T132.CD_CLIENTE_AAA WHEN '1' THEN 0 ELSE TPO.IM_COMISION_MXN END IM_COMISION_MXN, 
								CASE T132.CD_CLIENTE_AAA WHEN '1' THEN 0 ELSE TPO.IM_COMISION_EUR END IM_COMISION_EUR,
								CASE T132.CD_CANAL WHEN 2 THEN 1 ELSE 2 END Fila
					FROM TGM053_TIPO_OP_MX TPO, TGM132_CTARL_MX94X T132
					INNER JOIN TGM042_MONEDA_MX MND ON T132.CD_MONEDA = MND.CD_MONEDA
					INNER JOIN TGM041_IVA_MX IVA ON T132.CD_IVA = IVA.CD_IVA
					WHERE  T132.CD_MENSUALIDAD = 1 AND T132.TM_BAJA IS NULL
					AND T132.CD_MT941 = '1' AND TPO.TP_MENSAJE = '941') MT941, 
					(SELECT Rownum AS Fila FROM TGM132_CTARL_MX94X) Repetir
		WHERE MT941.Fila >= Repetir.Fila
		UNION ALL 
		SELECT MT942.NB_CUENTA NB_CUENTA , MT942.NU_CODIGO_SICOCO, MT942.TX_TP_OPERACION, MT942.CD_REFERENCIA_BNC, 
						MT942.NU_OPERACIONES,  MT942.NB_MONEDA, MT942.CD_CLIENTE_AAA, MT942.NU_PORCENTAJE,                      
						MT942.IM_COMISION_USD, MT942.IM_COMISION_MXN, MT942.IM_COMISION_EUR   
		FROM (SELECT  SUBSTR(T132.NB_CTA_COMISIONES,1,10) NB_CUENTA, TPO.NU_CODIGO_SICOCO, TPO.TX_TP_OPERACION, T132.CD_REFERENCIA_BNC, 
								1 AS NU_OPERACIONES,  MND.NB_MONEDA, T132.CD_CLIENTE_AAA,IVA.NU_PORCENTAJE,                      
								CASE T132.CD_CLIENTE_AAA WHEN '1' THEN 0 ELSE TPO.IM_COMISION_USD END IM_COMISION_USD,
								CASE T132.CD_CLIENTE_AAA WHEN '1' THEN 0 ELSE TPO.IM_COMISION_MXN END IM_COMISION_MXN, 
								CASE T132.CD_CLIENTE_AAA WHEN '1' THEN 0 ELSE TPO.IM_COMISION_EUR END IM_COMISION_EUR,
								CASE T132.CD_CANAL WHEN 2 THEN 1 ELSE 2 END Fila
					FROM TGM053_TIPO_OP_MX TPO, TGM132_CTARL_MX94X T132
					INNER JOIN TGM042_MONEDA_MX MND ON T132.CD_MONEDA = MND.CD_MONEDA
					INNER JOIN TGM041_IVA_MX IVA ON T132.CD_IVA = IVA.CD_IVA
					WHERE  T132.CD_MENSUALIDAD = 1 AND T132.TM_BAJA IS NULL 
					AND T132.CD_MT942 = '1' AND TPO.TP_MENSAJE = '942') MT942, 
					(SELECT Rownum AS Fila FROM TGM132_CTARL_MX94X) Repetir
		WHERE MT942.Fila >= Repetir.Fila
		ORDER BY NB_CUENTA;
	 END SP_132S_SICOCO_94X;
	 
END PG_MX_SICOCO_MT94X;
