create or replace PROCEDURE           "SP_IGM048_PROC_LOG" (TX_AUX OUT NOCOPY VARCHAR2, PCD_PROCESO_GIS IN NUMBER, PCD_TP_EVENTO IN NUMBER, PTX_PROCESO_LOG IN VARCHAR2) AS
BEGIN
  INSERT INTO TGM048_PROCESO_LOG(CD_TP_EVENTO, CD_PROCESO_GIS, TX_PROCESO_LOG, TM_PROCESO_LOG)
  VALUES(PCD_TP_EVENTO, PCD_PROCESO_GIS, PTX_PROCESO_LOG, SYSTIMESTAMP);
  
  COMMIT;
  
  TX_AUX := 'OK';
END;