  CREATE SEQUENCE  "MONITOR"."SQ_GM023_USUARIO"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "MONITOR"."SQ_GM006_PAIS"  MINVALUE 0 MAXVALUE 999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "MONITOR"."SQ_GM015_AVISO"  MINVALUE 0 MAXVALUE 99 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  CYCLE ;
   CREATE SEQUENCE  "MONITOR"."SQ_GM017_SECCION"  MINVALUE 0 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "MONITOR"."SQ_GM020_LIGA"  MINVALUE 0 MAXVALUE 99999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "MONITOR"."SQ_GM018_SUBSECC"  MINVALUE 0 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ; 
   CREATE SEQUENCE  "MONITOR"."SQ_GM016_GRUPO_USR"  MINVALUE 0 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
 
  CREATE TABLE "MONITOR"."TGM023_USUARIO" 
   (	"CD_USUARIO" NUMBER(8,0), 
	"CD_PAIS" NUMBER(3,0), 
	"CD_CLAVE_USUARIO" VARCHAR2(10 BYTE), 
	"CD_CONTRASENIA" VARCHAR2(45 BYTE), 
	"NB_NOMBRE_USR" VARCHAR2(80 BYTE), 
	"NB_APELL_PAT" VARCHAR2(35 BYTE), 
	"NB_APELL_MAT" VARCHAR2(35 BYTE), 
	"NU_EXTENSION" NUMBER(5,0), 
	"TX_CORREO_ELECTR" VARCHAR2(50 BYTE), 
	"CT_CONEX_LIMITE" NUMBER(3,0), 
	"CT_LOGEO_ERRONEO" NUMBER(3,0), 
	"CT_CONEX_ACTIVAS" NUMBER(3,0), 
	"TM_CAMBIO_CNTRASEN" TIMESTAMP (6), 
	"TM_ULTIMO_ACCESO" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE OR REPLACE TRIGGER "MONITOR"."TGBI_GM023_USUARIO" 
 BEFORE INSERT ON TGM023_USUARIO
 FOR EACH ROW
BEGIN
 SELECT SQ_GM023_USUARIO.NEXTVAL INTO :NEW.CD_USUARIO FROM DUAL;
END;
/
ALTER TRIGGER "MONITOR"."TGBI_GM023_USUARIO" ENABLE;



  CREATE TABLE "MONITOR"."TGM006_PAIS" 
   (	"CD_PAIS" NUMBER(3,0), 
	"NB_PAIS" CHAR(2 BYTE), 
	"TX_PAIS" VARCHAR2(35 BYTE), 
	"CD_BANCO_INTERNO" CHAR(4 BYTE), 
	"NB_PAIS_CCR" VARCHAR2(25 BYTE), 
	"NB_BIC" CHAR(8 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE OR REPLACE TRIGGER "MONITOR"."TGBI_GM006_PAIS" 
 BEFORE INSERT ON TGM006_PAIS
 FOR EACH ROW
BEGIN
 SELECT SQ_GM006_PAIS.NEXTVAL INTO :NEW.CD_PAIS FROM DUAL;
END;
/
ALTER TRIGGER "MONITOR"."TGBI_GM006_PAIS" DISABLE;
 
 
 CREATE TABLE "MONITOR"."TGM026_DESBLOQ_USR" 
   (	"CD_USUARIO" NUMBER(8,0), 
	"TM_REGISTRO_DESBL" TIMESTAMP (6), 
	"TX_PREGUNTA1" VARCHAR2(35 BYTE), 
	"TX_RESPUESTA1" VARCHAR2(35 BYTE), 
	"TX_PREGUNTA2" VARCHAR2(35 BYTE), 
	"TX_RESPUESTA2" VARCHAR2(35 BYTE), 
	"TX_PREGUNTA3" VARCHAR2(35 BYTE), 
	"TX_RESPUESTA3" VARCHAR2(35 BYTE), 
	"TM_ULTIMO_DESBLOQ" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 																				
 																				
 CREATE TABLE "MONITOR"."TGM015_AVISO" 
   (	"CD_AVISO" NUMBER(2,0), 
	"TX_AVISO" VARCHAR2(550 BYTE), 
	"TM_ALTA" TIMESTAMP (6)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE OR REPLACE TRIGGER "MONITOR"."TGBI_GM015_AVISO" 
 BEFORE INSERT ON TGM015_AVISO
 FOR EACH ROW
BEGIN
 SELECT SQ_GM015_AVISO.NEXTVAL INTO :NEW.CD_AVISO FROM DUAL;
END;
/
ALTER TRIGGER "MONITOR"."TGBI_GM015_AVISO" ENABLE;

CREATE TABLE "MONITOR"."TGM017_SECCION" 
   (	"CD_SECCION" NUMBER(5,0), 
	"NB_SECCION" VARCHAR2(50 BYTE), 
	"NU_ORDEN" NUMBER(3,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE OR REPLACE TRIGGER "MONITOR"."TGBI_GM017_SECCION" 
 BEFORE INSERT ON TGM017_SECCION
 FOR EACH ROW
BEGIN
 SELECT SQ_GM017_SECCION.NEXTVAL INTO :NEW.CD_SECCION FROM DUAL;
END;
/
ALTER TRIGGER "MONITOR"."TGBI_GM017_SECCION" ENABLE;
 
  CREATE TABLE "MONITOR"."TGM020_LIGA" 
   (	"CD_LIGA" NUMBER(8,0), 
	"CD_PAIS" NUMBER(3,0), 
	"CD_SECCION" NUMBER(5,0), 
	"CD_SUBSECCION" NUMBER(5,0), 
	"CD_TP_LIGA" NUMBER(2,0), 
	"NB_LIGA" VARCHAR2(30 BYTE), 
	"NB_RUTA_LIGA" VARCHAR2(200 BYTE), 
	"NU_ORDEN" NUMBER(3,0), 
	"TP_LIGA_PRIVADA" CHAR(1 BYTE), 
	"TX_LIGA" VARCHAR2(255 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE OR REPLACE TRIGGER "MONITOR"."TGBI_GM020_LIGA" 
 BEFORE INSERT ON TGM020_LIGA
 FOR EACH ROW
BEGIN
 SELECT SQ_GM020_LIGA.NEXTVAL INTO :NEW.CD_LIGA FROM DUAL;
END;
/
ALTER TRIGGER "MONITOR"."TGBI_GM020_LIGA" ENABLE;
 
 
   CREATE TABLE "MONITOR"."TGM018_SUBSECCION" 
   (	"CD_SUBSECCION" NUMBER(5,0), 
	"CD_SECCION" NUMBER(5,0), 
	"NB_SUBSECCION" VARCHAR2(50 BYTE), 
	"NU_ORDEN" NUMBER(3,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE OR REPLACE TRIGGER "MONITOR"."TGBI_GM018_SUBSECC" 
 BEFORE INSERT ON TGM018_SUBSECCION
 FOR EACH ROW
BEGIN
 SELECT SQ_GM018_SUBSECC.NEXTVAL INTO :NEW.CD_SUBSECCION FROM DUAL;
END;
/
ALTER TRIGGER "MONITOR"."TGBI_GM018_SUBSECC" ENABLE;
 
   CREATE TABLE "MONITOR"."TGM025_USUARIO_GRU" 
   (	"CD_USUARIO" NUMBER(8,0), 
	"CD_GRUPO" NUMBER(5,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
 
   CREATE TABLE "MONITOR"."TGM022_LIGA_GRUPO" 
   (	"CD_LIGA" NUMBER(8,0), 
	"CD_GRUPO" NUMBER(5,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
 
   CREATE TABLE "MONITOR"."TGM024_LIGA_USUARI" 
   (	"CD_LIGA" NUMBER(8,0), 
	"CD_USUARIO" NUMBER(8,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
  
  	
CREATE TABLE "MONITOR"."TGM016_GRUPO_USR" 
   (	"CD_GRUPO" NUMBER(5,0), 
	"NB_GRUPO" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE OR REPLACE TRIGGER "MONITOR"."TGBI_GM016_GRUPO_USR" 
 BEFORE INSERT ON TGM016_GRUPO_USR
 FOR EACH ROW
BEGIN
 SELECT SQ_GM016_GRUPO_USR.NEXTVAL INTO :NEW.CD_GRUPO FROM DUAL;
END;
/
ALTER TRIGGER "MONITOR"."TGBI_GM016_GRUPO_USR" ENABLE;
 
 
 

--Stores
create or replace PROCEDURE "SP_GM015_INS_AVISO" (nombre IN CHAR) as
BEGIN
  INSERT INTO TGM015_AVISO (TX_AVISO, TM_ALTA) VALUES (nombre,SYSDATE);
END;
/
create or replace PROCEDURE "SP_GM015_UPD_AVISO" (nameAviso IN CHAR, idAviso IN CHAR) as
BEGIN
    update TGM015_AVISO set TX_AVISO=nameAviso, TM_ALTA=SYSDATE where CD_AVISO=idAviso;
END;
/
create or replace PROCEDURE "SP_GM015_DEL_AVISO" (idAviso IN INTEGER) as
BEGIN
    DELETE FROM TGM015_AVISO WHERE CD_AVISO = idAviso;
END;
/


create or replace PROCEDURE "SP_GM023_UPD_USRPWD" (idUser IN INTEGER, pass IN CHAR) as
BEGIN
    UPDATE TGM023_USUARIO
SET    CD_CONTRASENIA     = pass,     
       TM_CAMBIO_CNTRASEN = SYSDATE
WHERE  CD_USUARIO         = idUser;
END;
/
create or replace PROCEDURE "SP_GM023_CLOSE_SES" (IN_USERNAME IN CHAR) as
    X_SESSIONS NUMBER;
BEGIN

    SELECT CT_CONEX_ACTIVAS INTO X_SESSIONS FROM TGM023_USUARIO usr WHERE usr.CD_CLAVE_USUARIO = IN_USERNAME;

    IF X_SESSIONS > 0 THEN
       X_SESSIONS := X_SESSIONS -1;
    ELSE
       X_SESSIONS := 0;
    END IF;

    UPDATE TGM023_USUARIO set CT_CONEX_ACTIVAS = X_SESSIONS where CD_CLAVE_USUARIO = IN_USERNAME;
    COMMIT;
    EXCEPTION
     WHEN OTHERS THEN
         ROLLBACK;
         X_SESSIONS := 0 ;
END; 
/
create or replace PROCEDURE "SP_GM026_INS_DESBLOQ_USER" (
NU_USUARIO_VAR IN NUMBER,
TX_PREGUNTA1_VAR IN VARCHAR2,
TX_RESPUESTA1_VAR IN VARCHAR2,
TX_PREGUNTA2_VAR IN VARCHAR2,
TX_RESPUESTA2_VAR IN VARCHAR2,
TX_PREGUNTA3_VAR IN VARCHAR2,
TX_RESPUESTA3_VAR IN VARCHAR2
) as
BEGIN
  INSERT INTO TGM026_DESBLOQ_USR DESB
    (DESB.CD_USUARIO, DESB.TM_REGISTRO_DESBL, DESB.TX_PREGUNTA1, DESB.TX_RESPUESTA1,DESB.TX_PREGUNTA2,DESB.TX_RESPUESTA2,DESB.TX_PREGUNTA3,DESB.TX_RESPUESTA3,DESB.TM_ULTIMO_DESBLOQ) 
    VALUES 
    (NU_USUARIO_VAR, SYSDATE, TX_PREGUNTA1_VAR, TX_RESPUESTA1_VAR, TX_PREGUNTA2_VAR, TX_RESPUESTA2_VAR, TX_PREGUNTA3_VAR, TX_RESPUESTA3_VAR, SYSDATE);
END;
/