//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package services.generico;

import javax.xml.ws.WebFault;

@WebFault(name = "ARMXException", targetNamespace = "http://excepciones.armx.bbva.com")
public class ARMXException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.bbva.armx.excepciones.ARMXException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ARMXException(String message, com.bbva.armx.excepciones.ARMXException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public ARMXException(String message, com.bbva.armx.excepciones.ARMXException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.bbva.armx.excepciones.ARMXException
     */
    public com.bbva.armx.excepciones.ARMXException getFaultInfo() {
        return faultInfo;
    }

}
