//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package services.generico;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.bbva.armx.vo.RespuestaAEVo;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ejecutaTxHostReturn" type="{http://VO.armx.bbva.com}RespuestaAEVo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ejecutaTxHostReturn"
})
@XmlRootElement(name = "ejecutaTxHostResponse")
public class EjecutaTxHostResponse {

    @XmlElement(required = true, nillable = true)
    protected RespuestaAEVo ejecutaTxHostReturn;

    /**
     * Gets the value of the ejecutaTxHostReturn property.
     * 
     * @return
     *     possible object is
     *     {@link RespuestaAEVo }
     *     
     */
    public RespuestaAEVo getEjecutaTxHostReturn() {
        return ejecutaTxHostReturn;
    }

    /**
     * Sets the value of the ejecutaTxHostReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link RespuestaAEVo }
     *     
     */
    public void setEjecutaTxHostReturn(RespuestaAEVo value) {
        this.ejecutaTxHostReturn = value;
    }

}
