//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package services.generico;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the services.generico package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: services.generico
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EjecutaTxHostResponse }
     * 
     */
    public EjecutaTxHostResponse createEjecutaTxHostResponse() {
        return new EjecutaTxHostResponse();
    }

    /**
     * Create an instance of {@link GetListaTx }
     * 
     */
    public GetListaTx createGetListaTx() {
        return new GetListaTx();
    }

    /**
     * Create an instance of {@link SetTrackingH2HResponse }
     * 
     */
    public SetTrackingH2HResponse createSetTrackingH2HResponse() {
        return new SetTrackingH2HResponse();
    }

    /**
     * Create an instance of {@link GetParametros }
     * 
     */
    public GetParametros createGetParametros() {
        return new GetParametros();
    }

    /**
     * Create an instance of {@link SetTrackingH2H }
     * 
     */
    public SetTrackingH2H createSetTrackingH2H() {
        return new SetTrackingH2H();
    }

    /**
     * Create an instance of {@link GetListaTxResponse }
     * 
     */
    public GetListaTxResponse createGetListaTxResponse() {
        return new GetListaTxResponse();
    }

    /**
     * Create an instance of {@link EjecutaTxHost }
     * 
     */
    public EjecutaTxHost createEjecutaTxHost() {
        return new EjecutaTxHost();
    }

    /**
     * Create an instance of {@link GetParametrosResponse }
     * 
     */
    public GetParametrosResponse createGetParametrosResponse() {
        return new GetParametrosResponse();
    }

}
