//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package services.generico;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.bbva.armx.vo.RespuestaAEVo;
import org.apache.xml.xml_soap.Map;

@WebService(name = "TransaccionHost_service", targetNamespace = "http://generico.services")
@XmlSeeAlso({
    com.bbva.armx.vo.ObjectFactory.class,
    services.generico.ObjectFactory.class,
    com.bbva.armx.excepciones.ObjectFactory.class,
    org.apache.xml.xml_soap.ObjectFactory.class
})
public interface TransaccionHostService {


    /**
     * 
     * @param params
     * @param opcion
     * @param usuario
     * @param aplicacion
     * @return
     *     returns com.bbva.armx.vo.RespuestaAEVo
     * @throws ARMXException
     */
    @WebMethod
    @WebResult(name = "getListaTxReturn", targetNamespace = "")
    @RequestWrapper(localName = "getListaTx", targetNamespace = "http://generico.services", className = "services.generico.GetListaTx")
    @ResponseWrapper(localName = "getListaTxResponse", targetNamespace = "http://generico.services", className = "services.generico.GetListaTxResponse")
    public RespuestaAEVo getListaTx(
        @WebParam(name = "aplicacion", targetNamespace = "")
        String aplicacion,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "opcion", targetNamespace = "")
        String opcion,
        @WebParam(name = "params", targetNamespace = "")
        Map params)
        throws ARMXException
    ;

    /**
     * 
     * @param params
     * @param opcion
     * @param usuario
     * @param aplicacion
     * @return
     *     returns com.bbva.armx.vo.RespuestaAEVo
     * @throws ARMXException
     */
    @WebMethod
    @WebResult(name = "ejecutaTxHostReturn", targetNamespace = "")
    @RequestWrapper(localName = "ejecutaTxHost", targetNamespace = "http://generico.services", className = "services.generico.EjecutaTxHost")
    @ResponseWrapper(localName = "ejecutaTxHostResponse", targetNamespace = "http://generico.services", className = "services.generico.EjecutaTxHostResponse")
    public RespuestaAEVo ejecutaTxHost(
        @WebParam(name = "aplicacion", targetNamespace = "")
        String aplicacion,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "opcion", targetNamespace = "")
        String opcion,
        @WebParam(name = "params", targetNamespace = "")
        Map params)
        throws ARMXException
    ;

    /**
     * 
     * @param params
     * @param opcion
     * @param usuario
     * @param aplicacion
     * @return
     *     returns com.bbva.armx.vo.RespuestaAEVo
     * @throws ARMXException
     */
    @WebMethod
    @WebResult(name = "getParametrosReturn", targetNamespace = "")
    @RequestWrapper(localName = "getParametros", targetNamespace = "http://generico.services", className = "services.generico.GetParametros")
    @ResponseWrapper(localName = "getParametrosResponse", targetNamespace = "http://generico.services", className = "services.generico.GetParametrosResponse")
    public RespuestaAEVo getParametros(
        @WebParam(name = "aplicacion", targetNamespace = "")
        String aplicacion,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "opcion", targetNamespace = "")
        String opcion,
        @WebParam(name = "params", targetNamespace = "")
        Map params)
        throws ARMXException
    ;

    /**
     * 
     * @param params
     * @param opcion
     * @param usuario
     * @param aplicacion
     * @return
     *     returns com.bbva.armx.vo.RespuestaAEVo
     * @throws ARMXException
     */
    @WebMethod
    @WebResult(name = "setTrackingH2HReturn", targetNamespace = "")
    @RequestWrapper(localName = "setTrackingH2H", targetNamespace = "http://generico.services", className = "services.generico.SetTrackingH2H")
    @ResponseWrapper(localName = "setTrackingH2HResponse", targetNamespace = "http://generico.services", className = "services.generico.SetTrackingH2HResponse")
    public RespuestaAEVo setTrackingH2H(
        @WebParam(name = "aplicacion", targetNamespace = "")
        String aplicacion,
        @WebParam(name = "usuario", targetNamespace = "")
        String usuario,
        @WebParam(name = "opcion", targetNamespace = "")
        String opcion,
        @WebParam(name = "params", targetNamespace = "")
        Map params)
        throws ARMXException
    ;

}
